Update docker_utils.py
Fix `AttributeError: 'str' object has no attribute 'decode'`
If `c` is a string, we do not need to decode (and it will throw an error if we try to).
Error was thrown by running `dts duckiebot evaluate --native`